---
- name: Create a VM on HyperV
  hosts: all

  vars:
    #remote_iso_url: https://rh-edge-tarballs-prod.s3.us-east-1.amazonaws.com/5910538/isos/kemos-pretty-edge-server.iso

    vm_name: my-pretty-edge-server
    vm_memory: "8GB"
    vm_cpus: 4
    vm_disk_size: "20GB"
    vm_network_switch: VMNetwork

  tasks:
  
    - name: Download a remote ISO
      when: remote_iso_url is defined
      block:
      #- name: Set fact for the file name of the ISO
      #  set_fact:
      #    fname: "{{ remote_iso_url | basename }}"

      - name: Download the ISO
        ansible.builtin.get_url:
          url: "{{ remote_iso_url }}"
          dest: "/tmp/"
        register: r_iso_download
          
      - name: Set the local iso fact
        set_fact:
          iso_path_loc: "{{ r_iso_download.dest }}"

    - name: Destroy a VM if it exists
      include_role:
        name: rhel-edge-on-hyperv
      vars:
        vm_state: absent

    - name: Create a VM
      include_role:
        name: rhel-edge-on-hyperv
      vars:
        vm_state: started
